.enc "DialogueCharacters"

;	Not used in our formatting, but might as well define them.
.edef "§00", $00
.edef "[exit]", $01
.edef "[n]", $02
.edef "[sh]", $03
.edef "[cs]", $04
.edef "[dummy05]", $05
.edef "[TWinTop]", $06
.edef "[TWinBtm]", $07
.edef "[k]", $08
.edef "[Tt]", $09
.edef "[Tt1]", $0A
.edef "[Tt2]", $0B
.edef "[Tt3]", $0C
.edef "[Tt4]", $0D
.edef "[Tt5]", $0E
.edef "[Tt6]", $0F

; Actual characters.
.edef "A", $10
.edef "B", $11
.edef "C", $12
.edef "D", $13
.edef "E", $14
.edef "F", $15
.edef "G", $16
.edef "H", $17
.edef "I", $18
.edef "J", $19
.edef "K", $1A
.edef "L", $1B
.edef "M", $1C
.edef "N", $1D
.edef "O", $1E
.edef "P", $1F
.edef "Q", $20
.edef "R", $21
.edef "S", $22
.edef "T", $23
.edef "U", $24
.edef "V", $25
.edef "W", $26
.edef "X", $27
.edef "Y", $28
.edef "Z", $29
.edef "a", $2A
.edef "b", $2B
.edef "c", $2C
.edef "d", $2D
.edef "e", $2E
.edef "f", $2F
.edef "g", $30
.edef "h", $31
.edef "i", $32
.edef "j", $33
.edef "k", $34
.edef "l", $35
.edef "m", $36
.edef "n", $37
.edef "o", $38
.edef "p", $39
.edef "q", $3A
.edef "r", $3B
.edef "s", $3C
.edef "t", $3D
.edef "u", $3E
.edef "v", $3F
.edef "w", $40
.edef "x", $41
.edef "y", $42
.edef "z", $43
.edef ".", $44
.edef "…", $444444		; Ellipsis character.
.edef ",", $45
.edef "?", $46
.edef "!", $47
.edef "'", $48			; Straight apostrophe
.edef "’", $48			; Curved apostrophe	
.edef "-", $49
.edef '"', $4A
.edef "·", $4B
.edef ":", $4C
.edef ";", $4D
.edef "(", $4E
.edef ")", $4F
.edef "0", $50
.edef "1", $51
.edef "2", $52
.edef "3", $53
.edef "4", $54
.edef "5", $55
.edef "6", $56
.edef "7", $57
.edef "8", $58
.edef "9", $59
.edef "$", $5A
.edef "%", $5B
.edef "&", $5C
.edef "*", $5D
.edef "+", $5E
.edef "/", $5F
.edef "“", $60
.edef "”", $61
.edef "=", $62
.edef "{[}", $63
.edef "♪", $64
.edef "{]}", $65
.edef "~", $66
.edef "ß", $67
.edef "¡", $68
.edef "¿", $69
.edef "À", $6A
.edef "Á", $6B
.edef "Â", $6C
.edef "Ã", $6D
.edef "Ä", $6E
.edef "Å", $6F
.edef "Æ", $70
.edef "Ç", $71
.edef "È", $72
.edef "É", $73
.edef "Ê", $74
.edef "Ë", $75
.edef "Ì", $76
.edef "Í", $77
.edef "Î", $78
.edef "Ï", $79
.edef "Ñ", $7A
.edef "{OE}", $7B
.edef "Ò", $7C
.edef "Ó", $7D
.edef "Ô", $7E
.edef "Õ", $7F
.edef "Ö", $80
.edef "Ø", $81
.edef "Ù", $82
.edef "Ú", $83
.edef "Û", $84
.edef "Ü", $85
.edef "Ý", $86
.edef "Ÿ", $87
.edef "à", $88
.edef "á", $89
.edef "â", $8A
.edef "ã", $8B
.edef "ä", $8C
.edef "å", $8D
.edef "æ", $8E
.edef "ç", $8F
.edef "è", $90
.edef "é", $91
.edef "ê", $92
.edef "ë", $93
.edef "ì", $94
.edef "í", $95
.edef "î", $96
.edef "ï", $97
.edef "ñ", $98
.edef "{oe}", $99
.edef "ò", $9A
.edef "ó", $9B
.edef "ô", $9C
.edef "õ", $9D
.edef "ö", $9E
.edef "ø", $9F
.edef "ù", $A0
.edef "ú", $A1
.edef "û", $A2
.edef "ü", $A3
.edef "ý", $A4
.edef "ÿ", $A5
.edef "§1_", $A6
.edef "§2_", $A7
.edef "§3_", $A8
.edef "§4_", $A9
.edef "§5_", $AA
.edef "§6_", $AB
.edef "§7_", $AC
.edef "§8_", $AD
.edef "§9_", $AE
.edef "§10_", $AF

.edef "¦", $AA
.edef "_", $AA

.edef " ", $BF
.edef " ", $BF

.edef "ð", $E0
.edef "{am}", $E1	; Slim "am" for Endgame's chapter title.
					; More dialogue characters can be added this way.