  Cavalier       .byte $01
  LanceKnight    .byte $01
  ArcherKnight      .byte $01
  AxeKnight      .byte $01
  FreeKnight     .byte $01
  Troubadour     .byte $01
  KnightLord     .byte $01
  Banneret     .byte $01
  MasterKnight   .byte $01
  Paladin        .byte $01
  PaladinF       .byte $01
  BowKnight     .byte $01
  Ranger         .byte $01
  MageKnight     .byte $01
  GreatKnight    .byte $01
  PegasusRider   .byte $02
  PegasusKnight  .byte $02
  FalconKnight   .byte $02
  WyvernRider    .byte $06
  WyvernKnight   .byte $06
  WyvernLord   .byte $06
  BowFighter         .byte $00
  SwordFighter       .byte $00
  Swordmaster    .byte $00
  Sniper         .byte $00
  Forester           .byte $00
  General        .byte $08
  Emperor        .byte $08
  Baron          .byte $08
  Soldier        .byte $00
  SpearSoldier   .byte $00
  AxeSoldier     .byte $00
  BowSoldier     .byte $00
  SwordSoldier   .byte $00
  LanceArmor     .byte $08
  AxeArmor       .byte $08
  BowArmor       .byte $08
  SwordArmor     .byte $08
  Barbarian      .byte $00
  AxeFighter     .byte $00
  Brigand        .byte $00
  Warrior        .byte $00
  Hunter         .byte $00
  Pirate         .byte $00
  Lordling     .byte $00
  MageFighter        .byte $10
  Prince         .byte $00
  Princess       .byte $00
  MageFighterF       .byte $10
  Queen          .byte $00
  Dancer         .byte $00
  Priest         .byte $00
  Mage           .byte $10
  FireMage       .byte $10
  ThunderMage    .byte $10
  WindMage       .byte $10
  HighPriest     .byte $10
  Bishop         .byte $10
  Sage           .byte $10
  Bard           .byte $00
  Shaman      .byte $00
  DarkMage       .byte $10
  DarkBishop     .byte $10
  Thief          .byte $00
  ThiefFighter          .byte $00
  Civilian       .byte $00
  Child          .byte $00
  Ballista       .byte $00
  IronBallista   .byte $00
  KillerBallista .byte $00
  GreatBallista  .byte $00
  DarkPrince     .byte $00