
  Sigurd    .byte $FF
  Naoise    .byte Paladin
  Alec      .byte Paladin
  Arden     .byte General
  Finn      .byte Banneret
  Quan      .byte $FF
  Midir     .byte BowKnight
  Lewyn     .byte Sage
  Chulainn  .byte Forester
  Azelle    .byte MageKnight
  Jamke     .byte Sniper
  Claud     .byte $FF
  Beowolf   .byte Ranger
  Lex       .byte GreatKnight
  Dew       .byte ThiefFighter
  Deirdre   .byte $FF
  Ethlyn    .byte PaladinF
  Lachesis  .byte MasterKnight
  Ayra      .byte Swordmaster
  Erinys    .byte FalconKnight
  Tailtiu   .byte MageFighterF
  Silvia    .byte $FF
  Edain     .byte HighPriest
  Brigid    .byte $FF
  Seliph    .byte KnightLord
  Shannan   .byte $FF
  Dalvin    .byte Forester
  Asaello   .byte Sniper
  Leif      .byte MasterKnight
  Iuchar    .byte GreatKnight
  Charlot   .byte HighPriest
  Hawk      .byte $FF
  Tristan   .byte Ranger
  AdultFinn   .byte Banneret
  Deimne    .byte BowKnight
  Hannibal  .byte $FF
  Ares      .byte Paladin
  Amid      .byte MageFighter
  Oifey     .byte Paladin
  Daisy     .byte ThiefFighter
  Creidne   .byte Forester
  Muirne    .byte HighPriest
  Julia     .byte Sage
  Altena    .byte WyvernLord
  Hermina   .byte FalconKnight
  Linda     .byte MageFighterF
  Laylea    .byte $FF
  Jeanne    .byte PaladinF
  Iucharba  .byte Warrior
  Scathach  .byte Forester
  Febail    .byte Sniper
  Coirpre   .byte HighPriest
  Ced       .byte $FF
  Diarmuid  .byte Ranger
  Lester    .byte BowKnight
  Arthur    .byte MageKnight
  Patty     .byte ThiefFighter
  Larcei    .byte Swordmaster
  Lana      .byte HighPriest
  Fee       .byte FalconKnight
  Tine      .byte MageFighterF
  Lene      .byte $FF
  Nanna     .byte PaladinF