None               .text "　\n"
PrayerSword        .text "じょせいせんよう\n"
ThiefSword         .text "ゴールドをぬすむ\n"
KillerBow          .text "　ひっさつ\n"
BarrierBlade       .text "まほうしゅび＋７\n"
Safeguard          .text "しゅびりょく＋７\n"
BerserkSword       .text "こんらんさせる\n"
BraveWeapon        .text "２回こうげき\n"
SilenceSword       .text "ちんもくさせる\n"
SleepSword         .text "ねむらせる\n"
FlameBrand         .text "＋エルファイアー\n"
LandsSword         .text "ＨＰをすいとる\n"
LevinSword         .text "＋エルサンダー\n"
WindSword          .text "＋エルウインド\n"
LightBrand         .text "＋ライトニング\n"
Mystletainn        .text "　ひっさつ\n"
Tyrfing            .text "　いのり\n"
HolyWeapon         .text "せんりょくアップ\n"
Yewfelle           .text "　ライブ\n"
Loptous            .text "こうげきはんげん\n"
Naga               .text "ロプトウスむこう\n"
IronbaneSword      .text "アーマー系に特効\n"
Ridersbane         .text "ナイト系に特効\n"
AntiFliers         .text "ひこう系に特効\n"
Hel                .text "ＨＰを１にさげる\n"
Nosferatu          .text "ＨＰをすいとる\n"
Heal               .text "ＨＰを回ふくする\n"
Mend               .text "ＨＰをおおく　　回ふくする\n"
Recover            .text "ＨＰをかんぜんに回ふくする\n"
Physic             .text "１０マスないの　みかたひとりに　ライブをかける\n"
Fortify            .text "１０マスないの　みかたぜんいんにライブをかける\n"
Return             .text "みかたひとりを　ほん城へもどす\n"
Warp               .text "みかたひとりを　じぐんのどれかの城にワープさせる\n"
Rescue             .text "１０マスないの　みかたひとりを　そばにひきよせる\n"
Restore            .text "１０マスないの　みかたひとりの　じょうたいを　　せいじょうにする\n"
Valkyrie           .text "\nんでしまった　みかたひとりを　よみがえらせる　ほん城でつかえる\n"	; PN cut this description out, it seems.
Silence            .text "１０マスないの　てきひとりの　　まほうをすうターンつかえなくする\n"
Sleep              .text "１０マスないの　てきひとりを　　すうターンうごけなくする\n"
Berserk            .text "１０マスないの　てきひとりを　　すうターンこんらんさせる\n"
Thief              .text "てきからゴールドをぬすむ\n"
HealBracelet        .text "まいターンＨＰが回ふくする\n"
ParagonRing        .text "けいけんちを　　２ばいもらえる\n"
ThiefBracelet          .text "てきからゴールドをぬすむ\n"
MiracleBracelet        .text "ピンチになると　かいひりつが　　あがる\n"
FollowUpRing        .text "あいてよりも　　みがるならば　　さいこうげき\n"
RecoverRing        .text "まいターンＨＰがぜん回ふくする\n"
BargainBracelet        .text "かいものやしゅうりのねだんがはんぶんになる\n"
KnightRing         .text "せんとうごにさいいどうできる\n"
ReturnRing         .text "ほん城にもどれる\n"
SpeedRing          .text "すばやさ＋５\n"
MagicRing          .text "まりょく＋５\n"
PowerRing          .text "ちから＋５\n"
ShieldRing         .text "しゅびりょく＋５\n"
BarrierRing        .text "まほうぼうぎょ　＋５\n"
LegRing            .text "いどうりょく＋３\n"
SkillRing          .text "わざ＋５\n"
Circlet            .text "せいれいのかみ　かざり　　　　　いのり＋ライブ\n"
